"""add post table

Revision ID: 92179c0a34e1
Revises: 226449598436
Create Date: 2024-07-03 14:09:26.268619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92179c0a34e1'
down_revision = '226449598436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
